name: "MCP Server"
version: "1.0.0"
slug: "mcp"
description: "Model Context Protocol Server for Home Assistant"
url: "https://github.com/tevonsb/homeassistant-mcp"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
init: false
map:
  - homeassistant_config
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: "MCP Server API port"
hassio_api: true
hassio_role: "admin"
homeassistant_api: true
auth_api: true
ingress: true
ingress_port: 3000
panel_icon: mdi:robot
panel_title: "MCP Server"
options:
  debug: false
  node_env: "production"
schema:
  debug: bool
  node_env: str
stage: "experimental"
webui: "http://[HOST]:[PORT:3000]"