# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: RUDY
version: "0.0.1"
slug: rudy
description: RUDY - Manage Remote USB Devices easilY
url: "https://github.com/Apocrathia/home-assistant-addons/tree/main/RUDY"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
apparmor: false
usb: true
udev: true
devicetree: true
devices:
  - /dev/bus/usb
map:
  - share:rw
kernel_modules: true
options:
  role: null
  usbip_server: null
  usbip_port: "3240"
  usbip_detach_orphans: true
  usbip_detach_all: true
  usbip_attach_delay: "3"
  usbip_device_ids: ""
  usbip_device_id_separator: ","
  usbip_sid_regex: false
  usbip_bus_ids: ""
  mqtt_host: "core-mosquitto"
  mqtt_port: "1883"
  mqtt_username: ""
  mqtt_password: ""
  mqtt_publish_topic: "rudy/client"
  mqtt_publish_options: ""
  mqtt_reload_on_topic: "rudy/server/start"
  mqtt_subscribe_options: ""
  mqtt_options: ""
  rudy_debug: false
  rudy_trace: false
schema:
  role: "list(client|server)"
  usbip_server: "str?"
  usbip_port: "port?"
  usbip_detach_orphans: "bool?"
  usbip_detach_all: "bool?"
  usbip_attach_delay: "int?"
  usbip_device_ids: "str?"
  usbip_device_id_separator: "str?"
  usbip_sid_regex: "bool?"
  usbip_bus_ids: "str?"
  mqtt_host: "str?"
  mqtt_port: "port?"
  mqtt_username: "str?"
  mqtt_password: "str?"
  mqtt_publish_topic: "str?"
  mqtt_publish_options: "str?"
  mqtt_reload_on_topic: "str?"
  mqtt_subscribe_options: "str?"
  mqtt_options: "str?"
  rudy_debug: "bool?"
  rudy_trace: "bool?"
